services:
  luau:
    image: golang:alpine
    working_dir: /app
    depends_on:
      - clients
    command: go run cmd/luau/main.go
    ports:
      - 8080:8080
    volumes:
      - "gohome:/go"
      - "gocache:/root/.cache/go-build"
      - .:/app

  demo:
    image: golang:alpine
    working_dir: /app
    command: go run demo.go
    ports:
      - 3000:3000
    volumes:
      - "gohome:/go"
      - "gocache:/root/.cache/go-build"
      - ./demo:/app

  clients:
    image: golang:alpine
    working_dir: /app/clients
    command: go run cmd/server/main.go
    ports:
      - 50051:50051
      - 50052:50052
    volumes:
      - "gohome:/go"
      - "gocache:/root/.cache/go-build"
      - .:/app

    healthcheck:
      test: ["CMD", "sh", "-c", "netstat -ltn | grep -c 50051"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 30s

  # locust:
  #   build: ./load-testing
  #   command: locust
  #   working_dir: /app
  #   volumes:
  #     - ./load-testing:/app
  #   ports:
  #   - 8089:8089

  # ghz:
  #   image: obvionaoe/ghz
  #   depends_on:
  #     - clients
  #   command: --insecure --proto=/ghz/protos/services.proto --call=clients.ClientService.Create --data-file='/opt/ghz/new.json' clients:50051
  #   volumes:
  #     - ./clients/clients:/ghz/protos
  #     - ./load-testing/new.json:/opt/ghz/new.json

  grpcox:
   image: gusaul/grpcox
   ports:
   - 6969:6969

volumes:
  gohome:
  gocache:
