syntax = "proto3";

package clients;

import "jose/jwk.proto";

option go_package = "github.com/G5Olivieri/luau/clients/clients";

enum GrantType {
  GRANT_TYPE_UNSPECIFIED = 0;
  GRANT_TYPE_AUTHORIZATION_CODE = 1;
  GRANT_TYPE_REFRESH_TOKEN = 2;
  GRANT_TYPE_PASSWORD = 3;
  GRANT_TYPE_CLIENT_CREDENTIALS = 4;
}

enum ResponseType {
  RESPONSE_TYPE_UNSPECIFIED = 0;
  RESPONSE_TYPE_CODE = 1;
  RESPONSE_TYPE_ID_TOKEN = 2;
  RESPONSE_TYPE_ID_TOKEN_TOKEN = 3;
  RESPONSE_TYPE_CODE_TOKEN = 4;
  RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN = 5;
}

enum TokenEndpointAuthMethod {
  TOKEN_ENDPOINT_AUTH_METHOD_UNSPECIFIED = 0;
  TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST = 1;
  TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC = 2;
  TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_JWT = 3;
  TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT = 4;
  TOKEN_ENDPOINT_AUTH_METHOD_NONE = 5;
}

enum ApplicationType {
  APPLICATION_TYPE_UNSPECIFIED = 0;
  APPLICATION_TYPE_NATIVE = 1;
  APPLICATION_TYPE_WEB = 2;
}

enum SubjectType {
  SUBJECT_TYPE_UNSPECIFIED = 0;
  SUBJECT_TYPE_PUBLIC = 1;
  SUBJECT_TYPE_PAIRWISE = 2;
}

message CreateClientRequest {
  map<string, string> name = 1;
  repeated string redirect_uris = 2;
	repeated ResponseType response_types = 3;
	repeated GrantType grant_types = 4;
  int32 default_max_age = 5;
  repeated string contacts = 6;
  TokenEndpointAuthMethod token_endpoint_auth_method = 7;
  ApplicationType application_type = 8;
  map<string, string> logo_uri = 9;
  map<string, string> client_uri = 10;
  map<string, string> policy_uri = 11;
  map<string, string> tos_uri = 12;
  string jwks_uri = 13;
  repeated jose.JWK jwks = 14;
  string sector_identifier_uri = 15;
  SubjectType subject_type = 16;
  string id_token_signed_response_alg = 17;
  string id_token_encrypted_response_alg = 18;
  string id_token_encrypted_response_enc = 19;
  string userinfo_signed_response_alg = 20;
  string userinfo_encrypted_response_alg = 21;
  string userinfo_encrypted_response_enc = 22;
  string request_object_signing_alg = 23;
  string request_object_encryption_alg = 24;
  string request_object_encryption_enc = 25;
  string token_endpoint_auth_signing_alg = 26;
  bool require_auth_time = 27;
  repeated string default_acr_values = 28;
  string initiate_login_uri = 29;
  repeated string request_uris = 30;
}

message Client {
  string ID = 1;
  bytes secret = 2;
  map<string, string> name = 3;
  repeated string redirect_uris = 4;
	repeated ResponseType response_types = 5;
	repeated GrantType grant_types = 6;
  int32 default_max_age = 7;
  repeated string contacts = 8;
  TokenEndpointAuthMethod token_endpoint_auth_method = 9;
  ApplicationType application_type = 10;
  map<string, string> logo_uri = 11;
  map<string, string> client_uri = 12;
  map<string, string> policy_uri = 13;
  map<string, string> tos_uri = 14;
  string jwks_uri = 15;
  repeated jose.JWK jwks = 16;
  string sector_identifier_uri = 17;
  SubjectType subject_type = 18;
  string id_token_signed_response_alg = 19;
  string id_token_encrypted_response_alg = 20;
  string id_token_encrypted_response_enc = 21;
  string userinfo_signed_response_alg = 22;
  string userinfo_encrypted_response_alg = 23;
  string userinfo_encrypted_response_enc = 24;
  string request_object_signing_alg = 25;
  string request_object_encryption_alg = 26;
  string request_object_encryption_enc = 27;
  string token_endpoint_auth_signing_alg = 28;
  bool require_auth_time = 29;
  repeated string default_acr_values = 30;
  string initiate_login_uri = 31;
  repeated string request_uris = 32;
}
