definitions:
  adapters.restCreateOrUpdateUserRequest:
    properties:
      last_login:
        format: date-time
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  adapters.restUser:
    properties:
      id:
        format: uuid
        type: string
      last_login:
        format: date-time
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  adapters.restUsernamePassword:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: list users
      parameters:
      - default: 256
        description: 'limit items (max: 1024)'
        in: query
        name: limit
        type: integer
      - default: 0
        description: offset items
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/adapters.restUser'
              type: array
            type: array
        "400":
          description: Bad Request
      security:
      - OAuth2Application:
        - openid
      summary: list users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: create an user
      parameters:
      - description: create user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/adapters.restCreateOrUpdateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/adapters.restUser'
        "400":
          description: Bad Request
      security:
      - OAuth2Application:
        - openid
      summary: create an user
      tags:
      - users
  /{id}:
    delete:
      consumes:
      - application/json
      description: delete an user by id
      parameters:
      - description: user id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "404":
          description: Not Found
      security:
      - OAuth2Application:
        - openid
      summary: delete user by id
      tags:
      - users
    get:
      consumes:
      - application/json
      description: get an user by id
      parameters:
      - description: user id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters.restUser'
        "404":
          description: Not Found
      security:
      - OAuth2Application:
        - openid
      summary: get user by id
      tags:
      - users
    put:
      consumes:
      - application/json
      description: update an user
      parameters:
      - description: user id
        format: uuid
        in: path
        name: id
        required: true
        type: string
      - description: update user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/adapters.restCreateOrUpdateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters.restUser'
        "404":
          description: Not Found
      security:
      - OAuth2Application:
        - openid
      summary: update user
      tags:
      - users
  /username-password:
    post:
      consumes:
      - application/json
      description: get an user by username and password
      parameters:
      - description: username and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/adapters.restUsernamePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters.restUser'
        "404":
          description: Not Found
      security:
      - OAuth2Application:
        - openid
      summary: get user by username and password
      tags:
      - users
  /username/{username}:
    get:
      consumes:
      - application/json
      description: get an user by username
      parameters:
      - description: user username
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/adapters.restUser'
        "404":
          description: Not Found
      security:
      - OAuth2Application:
        - openid
      summary: get user by username
      tags:
      - users
securityDefinitions:
  OAuth2Application:
    authorizationUrl: http://localhost:8080/oidc/auth
    flow: accessCode
    scopes:
      openid: '"OpenID Connect scope"'
    tokenUrl: http://localhost:8080/oidc/token
    type: oauth2
swagger: "2.0"
