// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: kms_service.proto

package kms

import (
	context "context"
	jose "github.com/G5Olivieri/luau/jose/jose"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KMSService_GenerateKey_FullMethodName   = "/kms.KMSService/GenerateKey"
	KMSService_GetPublicKey_FullMethodName  = "/kms.KMSService/GetPublicKey"
	KMSService_Get_FullMethodName           = "/kms.KMSService/Get"
	KMSService_GetPublicKeys_FullMethodName = "/kms.KMSService/GetPublicKeys"
	KMSService_List_FullMethodName          = "/kms.KMSService/List"
	KMSService_Sign_FullMethodName          = "/kms.KMSService/Sign"
	KMSService_Verify_FullMethodName        = "/kms.KMSService/Verify"
)

// KMSServiceClient is the client API for KMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KMSServiceClient interface {
	GenerateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*jose.JWK, error)
	GetPublicKey(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*jose.JWK, error)
	Get(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*jose.JWK, error)
	GetPublicKeys(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*jose.JWKS, error)
	List(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*jose.JWKS, error)
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*wrapperspb.BytesValue, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
}

type kMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKMSServiceClient(cc grpc.ClientConnInterface) KMSServiceClient {
	return &kMSServiceClient{cc}
}

func (c *kMSServiceClient) GenerateKey(ctx context.Context, in *CreateKeyRequest, opts ...grpc.CallOption) (*jose.JWK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(jose.JWK)
	err := c.cc.Invoke(ctx, KMSService_GenerateKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) GetPublicKey(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*jose.JWK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(jose.JWK)
	err := c.cc.Invoke(ctx, KMSService_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) Get(ctx context.Context, in *wrapperspb.StringValue, opts ...grpc.CallOption) (*jose.JWK, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(jose.JWK)
	err := c.cc.Invoke(ctx, KMSService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) GetPublicKeys(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*jose.JWKS, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(jose.JWKS)
	err := c.cc.Invoke(ctx, KMSService_GetPublicKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) List(ctx context.Context, in *LimitOffset, opts ...grpc.CallOption) (*jose.JWKS, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(jose.JWKS)
	err := c.cc.Invoke(ctx, KMSService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*wrapperspb.BytesValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BytesValue)
	err := c.cc.Invoke(ctx, KMSService_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, KMSService_Verify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KMSServiceServer is the server API for KMSService service.
// All implementations must embed UnimplementedKMSServiceServer
// for forward compatibility.
type KMSServiceServer interface {
	GenerateKey(context.Context, *CreateKeyRequest) (*jose.JWK, error)
	GetPublicKey(context.Context, *wrapperspb.StringValue) (*jose.JWK, error)
	Get(context.Context, *wrapperspb.StringValue) (*jose.JWK, error)
	GetPublicKeys(context.Context, *LimitOffset) (*jose.JWKS, error)
	List(context.Context, *LimitOffset) (*jose.JWKS, error)
	Sign(context.Context, *SignRequest) (*wrapperspb.BytesValue, error)
	Verify(context.Context, *VerifyRequest) (*wrapperspb.BoolValue, error)
	mustEmbedUnimplementedKMSServiceServer()
}

// UnimplementedKMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKMSServiceServer struct{}

func (UnimplementedKMSServiceServer) GenerateKey(context.Context, *CreateKeyRequest) (*jose.JWK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKey not implemented")
}
func (UnimplementedKMSServiceServer) GetPublicKey(context.Context, *wrapperspb.StringValue) (*jose.JWK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedKMSServiceServer) Get(context.Context, *wrapperspb.StringValue) (*jose.JWK, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedKMSServiceServer) GetPublicKeys(context.Context, *LimitOffset) (*jose.JWKS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicKeys not implemented")
}
func (UnimplementedKMSServiceServer) List(context.Context, *LimitOffset) (*jose.JWKS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedKMSServiceServer) Sign(context.Context, *SignRequest) (*wrapperspb.BytesValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedKMSServiceServer) Verify(context.Context, *VerifyRequest) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedKMSServiceServer) mustEmbedUnimplementedKMSServiceServer() {}
func (UnimplementedKMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeKMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KMSServiceServer will
// result in compilation errors.
type UnsafeKMSServiceServer interface {
	mustEmbedUnimplementedKMSServiceServer()
}

func RegisterKMSServiceServer(s grpc.ServiceRegistrar, srv KMSServiceServer) {
	// If the following call pancis, it indicates UnimplementedKMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KMSService_ServiceDesc, srv)
}

func _KMSService_GenerateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).GenerateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_GenerateKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).GenerateKey(ctx, req.(*CreateKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).GetPublicKey(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.StringValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Get(ctx, req.(*wrapperspb.StringValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_GetPublicKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LimitOffset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).GetPublicKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_GetPublicKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).GetPublicKeys(ctx, req.(*LimitOffset))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LimitOffset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).List(ctx, req.(*LimitOffset))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KMSService_ServiceDesc is the grpc.ServiceDesc for KMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kms.KMSService",
	HandlerType: (*KMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKey",
			Handler:    _KMSService_GenerateKey_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _KMSService_GetPublicKey_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _KMSService_Get_Handler,
		},
		{
			MethodName: "GetPublicKeys",
			Handler:    _KMSService_GetPublicKeys_Handler,
		},
		{
			MethodName: "List",
			Handler:    _KMSService_List_Handler,
		},
		{
			MethodName: "Sign",
			Handler:    _KMSService_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _KMSService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kms_service.proto",
}
